<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="CreativityEventDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Aanwezig" Member="Aanwezigs">
    <Type Name="Aanwezig">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersoonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Aanwezig" Member="User" ThisKey="PersoonId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Event_Aanwezig" Member="Event" ThisKey="EventId" OtherKey="Id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="voornaam" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="gebruikersnaam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="wachtwoord" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="User_Aanwezig" Member="Aanwezigs" ThisKey="Id" OtherKey="PersoonId" Type="Aanwezig" />
      <Association Name="User_Event" Member="Events" ThisKey="Id" OtherKey="eigenaar" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="informatie" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="datum" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="visitors" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="eigenaar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sprekers" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Event_Aanwezig" Member="Aanwezigs" ThisKey="Id" OtherKey="EventId" Type="Aanwezig" />
      <Association Name="Event_Spreker" Member="Sprekers1" ThisKey="Id" OtherKey="event_id" Type="Spreker" />
      <Association Name="User_Event" Member="User" ThisKey="eigenaar" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Spreker" Member="Sprekers">
    <Type Name="Spreker">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="naam" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="tijd" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Event_Spreker" Member="Event" ThisKey="event_id" OtherKey="Id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
</Database>